# Generated by Django 6.1 on 2026-08-28 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('RT', 'Router'), ('SW', 'Switch'), ('FW', 'Firewall'), ('AP', 'Punto de acceso (AP)'), ('WC', 'Controlador WLAN'), ('SV', 'Servidor'), ('MD', 'Módem'), ('HB', 'Hub'), ('BR', 'Bridge'), ('LB', 'Balanceador de carga'), ('GW', 'Gateway'), ('RP', 'Repetidor'), ('IP', 'IDS/IPS'), ('UP', 'UPS'), ('NA', 'NAS'), ('IM', 'Impresora de red'), ('CM', 'Cámar IP'), ('TP', 'Teléfono IP'), ('ET', 'Estación de trabajo'), ('PP', 'Patch panel'), ('OT', 'Otro')], max_length=4)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=200)),
                ('ip_gestion', models.GenericIPAddressField()),
                ('ubicacion', models.TextField(max_length=300)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_puerto', models.CharField(max_length=15)),
                ('tipo', models.CharField(choices=[('FE', 'Fast Ethernet (10/100)'), ('GE', 'Gigabit Ethernet (1G)'), ('10G', '10 Gigabit Ethernet'), ('25G', '25 Gigabit Ethernet'), ('40G', '40 Gigabit Ethernet'), ('100G', '100 Gigabit Ethernet'), ('SFP', 'Fibra SFP'), ('SFP+', 'Fibra SFP+'), ('QSFP', 'Fibra QSFP'), ('CON', 'Consola (RJ45/RS232)'), ('USB', 'USB'), ('SER', 'Serial'), ('MGT', 'Puerto de gestión'), ('POE', 'PoE'), ('OT', 'Otro')], max_length=4)),
                ('velocidad', models.CharField(max_length=20)),
                ('estado', models.BooleanField()),
                ('conectado_a', models.CharField(blank=True, max_length=500, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puertos', to='crud.dispositivo')),
            ],
        ),
    ]
