# Generated by Django 6.1 on 2026-08-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puerto',
            name='numero_puerto',
            field=models.CharField(max_length=50),
        ),
    ]
