# Generated by Django 6.1 on 2026-08-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_puerto_numero_puerto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puerto',
            name='numero_puerto',
            field=models.CharField(max_length=20),
        ),
    ]
